### ISSUE TITLE
Publish updated package to PyPI

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#18]
# Tasks

* [x] Bump version up to `0.5.0`
* [x] Publish as `jsontableschema`
* [x] Update the packages for `jtskit` and `json-table-schema` o point to the new package going forward. 
  * Not exactly sure how this works, but we either a) get an actual redirect (unlikely) or b) publish an update to those packages that tells the user where the new package is.

**Comment by brew** [comment]
For the outdated packages, perhaps we could do something like this https://pypi.python.org/pypi/pypi-alias.

**Comment by pwalsh** [comment]
ok.

**Comment by brew** [comment]
A new version of json-table-schema has been uploaded PyPi to 'redirect' to jsontableschema. I'll do the same with jtskit once the PR for goodtables to upgrade jtskit to jsontableschema has been merged (https://github.com/okfn/goodtables/pull/62).

**Comment by pwalsh** [comment]
@brew thanks i merged GT now.
