### ISSUE TITLE
Use the available schema for validate, and only extend with code if required

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#24]
# Description 

The [validate function](https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/validate.py) takes a dict, and checks if it is a valid JSON Table Schema.

Currently, this check is completely coded in a procedural fashion. 

The preference was always to use the excellent [JSON Schema library in Python](https://python-jsonschema.readthedocs.org/en/latest/), in combination with [our JSON Schema description of how a JSON Table Schema should look](https://github.com/dataprotocols/schemas/blob/master/json-table-schema.json).

In the final version shipped, I did not do this due to parts of the spec that I could not represent easily as JSON Schema, and so this is what we got. I [wrote some notes on this here](https://github.com/dataprotocols/schemas/issues/5).

We want to change this now, use the JSON Schema spec + lib, and just add code for specific checks that we don't represent in the JSON Schema spec.

Aside: If you are confused about the difference between [JSON Schema](http://json-schema.org) and [JSON Table Schema](http://dataprotocols.org/json-table-schema/), these links might help.

# Tasks

* [x] Get familiar with the current state of the JSON Table Schema spec, and **update** https://github.com/dataprotocols/schemas/blob/master/json-table-schema.json as required (make PRs on the "spec as json schema")
* [x] We need to include the schema in the code. We can probably pull it in on install, rather than having it as part of the codebase directly? Or, probably better, we bump version of this lib for each change in spec, and include the json spec explicitly in the codebase.
* [x] Get rid of the current code in `validate`, and replace it with the `jsonschema` lib
  * [x] Add additional routines after the initial `jsonschema` validation for the things we are not checking using the schema itself
  * [x] Note that the error format will now change. We just want to go with how `jsonschema` reports errors so we'll have to change the API of `validate` accordingly, and be consistent with that for errors in custom code we write in the validate method
* [x] Fix/update/add tests

**Comment by pwalsh** [comment]
@trickvi we chatted on this a few weeks ago, so, as a user of this lib, and the `jsonschema` lib, do you have anything to add/suggest here? I want to make this change asap.

**Comment by joetsoi** [comment]
we could have the dataprotocols/schemas as a submodule of this repo, it would probably involve tagging commits inside the schemas to say "version blah" of the schema,

it's probably easiest just to include the json-table-schema.json file though.

**Comment by pwalsh** [comment]
@joetsoi let's just include it directly, and we'll bump the lib versions with each spec change.
