### ISSUE TITLE
Update based on current JSON Table Schema spec

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#25]
# Description

The JSON Table Schema spec is fluid. This library is currently the most comprehensive implementation of the spec, but we want to get to 100% feature coverage.

# Tasks

* [x] Check and implement coverage of `type` and `format` in line with current spec (http://dataprotocols.org/json-table-schema/#field-types-and-formats)
* [x] Check and implement coverage of `constraints` in line with current spec (http://dataprotocols.org/json-table-schema/#field-constraints)
* [x] <del>Check and implement coverage of `primaryKey`</del> #33
* [x] <del>Check and implement coverage of `foreignKeys` (which might be non-trivial, especially when considering JSON Table Schema as a standalone thing, outside of a Data Package. Let's assess)</del> #33
