### ISSUE TITLE
Better type casting/testing

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#26]
# Description

There are some inconsistencies in the type casting in the current code ([this issue provides some background](https://github.com/okfn/jsontableschema-py/issues/17)). 

We identified the need to have distinct `test` and `cast` methods. 

Additionally, @pudo pulled out some code from messytables to create the [`typecast`](https://github.com/pudo/typecast) lib (also mentioned in that thread).

We want to ensure we build on common work for all this tabular data stuff, and so, as discussed in #17 we'd like to use `typecast` as the basis of our `jsontableschema.types`. Some aspects of this integration are not completely clear: what should get pushed down into `typecast`, and what should stay here in the jsontableschema-specific lib.

So, our approach will be to:

* Fix the original casting/testing issues identified by copying the `test` `cast` API of `typecast`
* Implement this here for all JSON Table Schema Types/Formats (we have almost complete coverage here already)
* Once this is working and tested, use this as a basis on which to discuss pushing some of this down into `typecast`, and make `typecast` a dependency of `jsontableschema`

# Tasks

* [x] See the `test` / `cast` API of `typecast` and implement the same interface for each of our `jsontableschema.types`. Obviously the interaction between `type` and `format` here in `jsontableschema` is different from how `typecast` currently operates - so we don't seek to change this, rather, only the "public" test and cast API for types
* [x] Update `jsontableschema.models.SchemaModel` to support `test` and `cast`
  * [x] Rename `jsontableschema.models` to `jsontableschema.model` and `SchemaModel` to `Model`
* [x] Update test coverage for the API changes 
* [x] [This is a bug in the current code](https://github.com/okfn/jsontableschema-py/issues/16). It should get fixed as part of these changes.
