### ISSUE TITLE
Add "data" methods to Model

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#29]
# Description

The model should be immediately usable for common data conversion. Add public methods that transform a stream/iterator, and a row of data.

For simplicity, the API expects a iterable of arrays (or an iterable which is a single row) where values are either:

* a unicode string (string on Py3, unicode on Py2)
* the type being cast to (already transformed)

A later iteration could accept a file path or a raw CSV stream, but to do this we should first solve the issue of a common tabular data reader that can be used in MessyTables or GoodTables (https://github.com/okfn/tabulator-py/issues/1). Then, we can plug that in here.

# Tasks

* [x] Method for converting a single row
* [x] Method for converting an iterable and yielding rows
* [x] <del>Methods could support a strategy argument which is one of `cast` or `test`, which controls the response values as per the `cast` and `test` methods of `types`</del>
* [x] The method that handles iterables should support a `fail_fast` boolean. If true, raise on first error, if false, collect errors and return an error iterator when iteration ends (@pudo mentions `colander` and its [grouping of errors here](https://github.com/okfn/jsontableschema-py/issues/20#issuecomment-133894924)... worth checking)
* [x] Tests
